### ISSUE TITLE
is this capable of tracking high speed objects?

### ISSUE THREAD

**Issue by nyck33** [tobybreckon/python-examples-cv#2]
I tried to use the mouse click event to capture tennis players or the ball on broadcast TV tennis video files but it's too difficult while the video plays.

So I threw in a waitkey(0) but that does not work so well either.

I see HSV so is the state of whatever is being tracked just the HSV color of it?  

Ideally I'd like to use something like (x, y, HSV, x dot, y dot, x acc, y acc) as my state vector.

**Comment by tobybreckon** [comment]
Assuming you are referring to the Kalman filtering example .. not stated? ..

Yes, it can track high speed objects
 For your task I would perhaps suggest a condensation tracker (other repo) and am approach motion model for the dynamics of the ball. From where you are now, it appears some background reading on the tracking may be a good next step.

My state vector is speed and acceleration as per the code comments, you could add colour to the state in HSV or otherwise but would need an appropriate colour state update to be implemented.

**Comment by nyck33** [comment]
@tobybreckon thanks, I read over Ch.8 from the OpenCV book and I've done something similar with difference frames and blobs.  Can I ask one last question, what is "am approach motion model" per above and which lines in the code say "speed" or "acceleration"?  I could not find it.
