### ISSUE TITLE
kalman filter : error while showing predictions

### ISSUE THREAD

**Issue by ashwin-phadke** [tobybreckon/python-examples-cv#4]
OS : Fedora 32
Python : 3.8.5
Editor : VS Code

I am trying to implement the kalman filter example from your repository, however there seems to be some discrepancy while implementing the code at my end.

From the code below : 

https://github.com/tobybreckon/python-examples-cv/blob/3ed0aecf2ce199f9159026fd9c32bc26cc707e29/kalman_tracking_live.py#L324-L332

It needs to be changed to 

```
 prediction_x = [prediction[0] - (0.5 * w), prediction[1] - (0.5 * h)]
 prediction_y = [prediction[0] + (0.5 * w), prediction[1] + (0.5 * h)]
 frame = cv2.rectangle(frame, prediction_x, prediction_y, (0, 255, 0), 3)
```
i.e it requires passing as a list otherwise the line throws an error that only 2 positional arguments were passed hence missing the predictions for me.
After passing them as shown above a different error regarding `color` is shown as
If I keep prediction_x and prediction_y as tuples I get the following error

```
rame = cv2.rectangle(frame, prediction_x, prediction_y, (0, 255, 0), 3)
TypeError: function takes exactly 4 arguments (2 given)
```
So keeping them as lists the error shows up as

```   
frame = cv2.rectangle(frame, prediction_x, prediction_y, (0, 255, 0), 2)
TypeError: Scalar value for argument 'color' is not numeric
```

 I have tried multiple solutions like passing as a list, tuple , np.asscalar but none seem to work. As it would be a temporary fix commenting the line solves the issue.  How do I solve this?

**Comment by tobybreckon** [comment]
When I test this with the latest version of OpenCV (4.4, and have tested it recently with other versions), I get no such error from the original code. 

My usage of ``cv2.rectangle()`` conforms to the long-standing protoype for this function in the OpenCV manual - https://docs.opencv.org/master/d6/d6e/group__imgproc__draw.html#ga07d2f74cadcf8e305e810ce8eed13bc9 (which as far as I am aware has not changed recently in OpenCV, and is dependent on the OpenCV python interface rather than anything else such as Python version etc.)

It is also consistent with my usage of ``cv2.rectangle()`` in these examples:
https://github.com/tobybreckon/python-examples-cv/blob/master/cnn_ssd_detection.py
https://github.com/tobybreckon/python-examples-cv/blob/master/haar_cascade_detection.py
https://github.com/tobybreckon/python-examples-cv/blob/master/squeezenet.py
https://github.com/tobybreckon/python-examples-cv/blob/master/surf_detection.py
https://github.com/tobybreckon/python-examples-cv/blob/master/yolo.py
... which are in turn consistent with its usage elsewhere and the manual.

I do not think the lines you specify need to be changed because ...
-  I do not get an error and nor do my students who use the code in class
- my usage is consistent with the manual 
-  your proposed change itself introduces a different error with the usage of ``cv2.rectangle()`` that you are unable to overcome.

**Comment by ashwin-phadke** [comment]
I understand, I have not found any other issues in the script and also as I have too used cv2.rectangle() for a long time know that the code is conforming to best practices, however I just wanted to notify you about it. It works correctly in Windows without changing anything but the same code throws the error while running on Fedora. 
(I am on OpenCV - 4.3.0-dev compiled from source with contrib.)
I have posted a screenshot below.
![Screenshot from 2020-09-01 20-58-35](https://user-images.githubusercontent.com/23502062/91873387-8fcc4580-ec96-11ea-97e5-eb23f8c5d857.png)

**Comment by tobybreckon** [comment]
Mmm, strange. 

What is very strange is the error "takes 4 arguments (2 given)" when the line of code ``frame = ...`` in the same error message clearly shows 4 arguments passed ... ?

I note my original code - and indeed your corrected version passes 5 arguments - ``(frame, prediction_x, prediction_y, (0, 255, 0), 3)``. I suspect a python environment issue in VS code - have you tried running it from the command line as just:

```
python3 ./kalman_filter.py
```

If you get differing behaviour also try:

```
python3 ./version.py 
```
using https://github.com/tobybreckon/python-examples-ip/blob/master/version.py just to check it is not using an (older) system version of OpenCV or something. 

The only other difference I can see is that I have the ``camera_stream.py`` module in the same directory in order to avoid buffered camera input (message ``INFO: camera ....``) but that shouldn't effect things later on in the code unless it is not dislaying an image earlier or similar errors etc.

**Comment by ashwin-phadke** [comment]
> Mmm, strange.
> 
> What is very strange is the error "takes 4 arguments (2 given)" when the line of code `frame = ...` in the same error message clearly shows 4 arguments passed ... ?
> 
Yeah even I am confused by that.

> I note my original code - and indeed your corrected version passes 5 arguments - `(frame, prediction_x, prediction_y, (0, 255, 0), 3)`. I suspect a python environment issue in VS code - have you tried running it from the command line as just:
> 
Oh yeah I realized and corrected that issue, you can also see that in the screen-shot above I removed `3` and kept only 4 arguments , I just put up variables as prediction_x and prediction_y as the line was getting big but I am still passing them as tuples.
> ```
> python3 ./kalman_filter.py
> ```
> 
> If you get differing behaviour also try:
> 
> ```
> python3 ./version.py 
> ```
> 
> using https://github.com/tobybreckon/python-examples-ip/blob/master/version.py just to check it is not using an (older) system version of OpenCV or something.
> 
> The only other difference I can see is that I have the `camera_stream.py` module in the same directory in order to avoid buffered camera input (message `INFO: camera ....`) but that shouldn't effect things later on in the code unless it is not dislaying an image earlier or similar errors etc.

That INFO was generated as per my knowledge is because I was not passing command line arguments as I was debugging, If I run it regularly without debugging it executes well.

**Comment by ashwin-phadke** [comment]
![Screenshot from 2020-09-01 21-23-32](https://user-images.githubusercontent.com/23502062/91875670-6fea5100-ec99-11ea-888f-4ab2e71d1a96.png)

The issue still persists while running from terminal.

**Comment by ashwin-phadke** [comment]
![Screenshot from 2020-09-01 21-26-53](https://user-images.githubusercontent.com/23502062/91876062-e8511200-ec99-11ea-9a08-a536d97f5d10.png)

check_version.py output

**Comment by tobybreckon** [comment]
Does it get and display image from the camera? - you will be using the GSTREAMER backend by default it appears unless you use camera_stream.py

**Comment by ashwin-phadke** [comment]
Yeah I can see all the three windows, the camera stream window, the selected region window and the 3rd one with bars to adjust values(cannot remember the name).

Yeah got the window names.
 - hue histogram back propagation
 - initial selected region
 - kalman object tracking 

 I am getting the same issue even after using camera_stream.py

**Comment by tobybreckon** [comment]
Bizarre - sorry I don't have a solution, I am finding it impossible to replicate the error. 
Are you using the kalman...py code completely unmodified ?

**Comment by ashwin-phadke** [comment]
It is bizarre.
To verify again I did get all your code as is and tried to run it and I still get the same error.
It is strange to note that this same code works in Windows and not in Linux(Fedora in my case) also if I am passing 4 arguments how can the function say I have given only two.
Most Windows-Linux compatibility issues are related to path, file names, package versions etc but in this case it is a opencv function.

What platform are you using for this code?

**Comment by tobybreckon** [comment]
Locally - OpenSUSE but I have also tested on Debian and Ubuntu at the uni ... the code has been issued to ~60-80+ students as a demo annually since 2016, and the github history tells of no issues with ``cv2.rectangle()``. My students are quick to point out bugs in code professors provide ...

I am using python 3.5 / 3.6 / 3.7 for all my testing - not 3.8 but then its the OpenCV<->Python interface that is at fault here I think.
Do you the same error from one of the other demos using ``cv2.rectangle()`` ?  - sorry I think all of mine need external downloads (detailed at top of py file).

Sorry, I cannot be of more help on this one.

**Comment by ashwin-phadke** [comment]
I tried your yolo example and it works well, also I have many of my other projects(some even on my github) that I am using that requires OpenCV and also `cv2.rectangle()` many times apart from other functions, especially this project that uses dnn module like your yolo example https://github.com/ashwin-phadke/cvplayground but it works well too as it also has `cv2.rectangle` in it.
Maybe it's some interface issue as you mentioned.
Thanks for your help.

**Comment by tobybreckon** [comment]
See this issue - https://github.com/opencv/opencv/issues/15465 ... we were staring down the wrong error message.

The actual issue is the Kalman filter returns floating point predictions and I am adding a floating point half image width/height in L323 -> L331. It appears to affect Python 3.8 onwards which must implement stricter bindings / no auto casting to int or similar (?).

This is, of course, different to the int based use of ``cv2.rectangle()`` almost everywhere else in this repo, explaining the behaviour we were seeing for the Kalman example but not the others.

Now fixed and tested as suggested in the issue above - pull the latest version and let me know.

**Comment by ashwin-phadke** [comment]
Yes , this fixed it and it is working now, the opencv message surely needs fixing. Thank you for being proactive about this.
